version: '3.9'

services:
  backend:
    build: ./backend
    container_name: bandlink-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:@localhost:5432/BandLinkDB
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bandlink-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: BandLinkDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bandlink-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bandlink.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
